export const data = [
    {
        Entrada: {
            Receita1: {
                id: 0,
                Title: "Brusqueta de cogumelo paris",
                Tempo: "31min",
                Rendimento: "10 porções",
                Ingredientes: [
                    "Cogumelo Paris fresco",
                    "Azeite",
                    "Alho",
                    "Tomate-cereja",
                    "Sal",
                    "Pimenta-do-reino",
                    "Cheiro-verde",
                    "Baguete ou pão italiano",
                    "Parmesão",
                    "Mussarela ou queijo meia cura",
                    "Folhas de orégano",

                ],
                Quantidade: [
                    "200 gramas",
                    "2 colheres de sopa",
                    "3 dentes",
                    "200 gramas",
                    "a gosto",
                    "a gosto",
                    "a gosto",
                    "uma unidade",
                    "a gosto",
                    "a gosto",
                    "a gosto",
                ],
                Preparo: [
                    "Limpe os cogumelos, corte em lâminas e reserve.",
                    "Em uma panela, coloque o azeite e frite os dentes de alho.",
                    "Adicione os cogumelos, mexa e deixe refogar até ficarem levemente macios.",
                    "Junte os tomates cortados ao meio e refogue por aproximadamente um minuto.",
                    "Desligue o fogo e tempere com sal, pimenta, e cheiro-verde picado. Reserve.",
                    "Corte a baguete, distribua os pedaços em uma forma e leve para assar em forno preaquecido a 220 °C por dez minutos.",
                    "Com o pão ainda quente, esfregue um dente de alho por cima.",
                    "Regue com azeite cada fatia e coloque os pedaços de mussarela, o refogado de cogumelo e cubra com parmesão ou queijo meia cura.",
                    "Volte ao forno por aproximadamente cinco minutos ou até derreter o queijo.",
                    "Sirva com as folhas de orégano. Bom apetite.",
                ],


            },
            Receita2: {
                id: 1,
                Title: "Canapés de pão de queijo",
                Tempo: "50min",
                Rendimento: "8 porções",
                Ingredientes: [
                    "Pão de queijo congelado",
                    "Peito de peru",
                    "Ricota",
                    "1 colher de sopa de maionese",
                    "Creme de leite",
                    "Sal",
                    "Pimenta-do-reino",
                    "Pontas de cebolinha picada",
                    "damascos desidratados",
                ],
                Quantidade: [
                    "14 unidades",
                    "150 gramas",
                    "80 gramas",
                    "4 colheres de sopa",
                    "a gosto",
                    "a gosto",
                    "a gosto",
                    "2 unidades"
                ],
                Preparo: [
                    "Asse os pães de queijo no forno a 180 °C por cerca de 40 minutos.",
                    "Enquanto isso, coloque no processador o peito de peru com ricota, maionese, creme de leite, sal e pimenta-do-reino.",
                    "Bata tudo até obter uma textura de pasta.",
                    "Reserve na geladeira por 20 minutos.",
                    "Retire os pães de queijo do forno e corte-os ao meio.",
                    "Com os pães de queijo abertos, coloque o patê por cima de cada metade.",
                    "Corte os damascos em cubinhos e decore os canapés polvilhando por cima do patê.",
                    "Finalize decorando com as pontas de cebolinha.",
                    "Agora é só servir! Bom apetite.",
                ],
            },
            Receita3: {
                id: 2,
                Title: "Pera assada com catupiry de chuchu",
                Tempo: " 15min",
                Rendimento: "1 porção",
                Ingredientes: [
                    "Pera",
                    "Azeite de oliva",
                    "Sal",
                    "Pimenta-do-reino",
                    "Chuchu cozido no vapor",
                    "Inhame cozido no vapor",
                    "Nutritional yeast",
                    "Suco de limão",
                    "Azeite de oliva",
                    "Agar-agar"
                ],
                Quantidade: [
                    "1 unidade",
                    "5 ml",
                    "A gosto",
                    "A gosto",
                    "100 g",
                    "50 g",
                    "12 g",
                    "15 ml",
                    "10 ml",
                    "1 g"

                ],
                Preparo: [
                    "Corte a pera ao meio e retire toda a polpa.",
                    "Passe o azeite na pera.",
                    "Tempere com sal e pimenta.",
                    "Asse por 5 minutos em forno a 180°C",
                    "Retire do forno e reserve.",
                    "Coloque todos os ingredientes no liquidificador.",
                    "Bata até misturar tudo.",
                    "Despeje em uma panela.",
                    "Deixe no fogo por 2 minutos.",
                    "Recheie as peras com o catupiry.",
                    "Asse por mais 5 minutos no forno a 180°C.",
                ],
            },
            Receita4: {
                id: 3,
                Title: "Abóbora manteiga recheada com carne-seca",
                Tempo: "35min",
                Rendimento: " 1 porção",
                Ingredientes: [
                    "Abóbora manteiga",
                    "Azeite",
                    "Cebola picada",
                    "Alho",
                    "Carne seca desfiada",
                    "Queijo ralado",
                ],
                Quantidade: [
                    "1 unidade",
                    "A gosto",
                    "A gosto",
                    "A gosto",
                    "A gosto",
                    "A gosto",
                ],
                Preparo: [
                    "Corte a abóbora ao meio e retire as sementes.",
                    "Asse por 20 a 25 minutos em forno a 180 °C.",
                    "Após retirar a abóbora do forno, remova a polpa e reserve.",
                    "Em uma panela, coloque o azeite e refogue a cebola, o alho e a carne seca desfiada.",
                    "Adicione a polpa da abóbora.",
                    "Em seguida, recheie as metades da abóbora com o refogado.",
                    "Salpique queijo ralado por cima.",
                    "Retorne ao forno para gratinar.",
                    "Sirva e bom apetite.",

                ],
            }
        },
        EntradaVeg: {
            Entradaveg1: {
                id: 4,
                Title: "Bolo d agua",
                Tempo: "35min",
                Rendimento: " 12 porções",
                Ingredientes: [
                    "Açúcar",
                    "Óleo",
                    "Água",
                    "Chá de farinha de trigo",
                    "Fermento químico em pó",
                ],
                Quantidade: [
                    "1 xícara",
                    "1/2 xícara",
                    "250 ml",
                    "2 xícaras",
                    "1 colher"
                ],
                Preparo: [
                    "Em uma vasilha, coloque o açúcar, o óleo e bata bem.",
                    "Adicione a água aos poucos e continue batendo.",
                    "Acrescente a farinha peneirada e misture até ficar homogêneo.",
                    "Junte o fermento e misture delicadamente.",
                    "Transfira para uma forma untada e leve para assar em forno preaquecido a 180 °C por meia hora ou até dourar.",
                    "Aproveite cade pedaço dessa delícia .",

                ],
            },
            Entradaveg2: {
                id: 5,
                Title: "Vinagrete de jiló",
                Tempo: "30min",
                Rendimento: "4 porções",
                Ingredientes: [
                    "alho-poró fatiado",
                    "alho amassados",
                    "jilós cortados em brunoise (cubos bem pequenos)",
                    "Melado",
                    "Suco de meio limão",
                    "Molho umami",
                    "Sal",
                    "Pimenta-do-reino",

                ],
                Quantidade: [
                    "1 talo",
                    "2 dentes",
                    "2 unidades",
                    "1 colher de sopa",
                    "1/2 de limão",
                    "1 colher de sopa",
                    "1 pitada",
                    "a gosto"
                ],
                Preparo: [
                    "Em uma panela com água fervente, cozinhe o alho-poró com os dentes de alho por 10 minutos.",
                    "Em seguida, escorra e reserve o caldo para usar em outras receitas.",
                    "Coloque o alho-poró em água gelada para interromper o cozimento. Reserve.",
                    "Para o vinagrete, em uma vasilha, coloque o jiló, o melado, o suco de limão, o molho umami, o sal e a pimenta-do-reino.",
                    "Misture tudo muito bem e reserve.",
                    "Para o molho, cozinhe a polpa de maracujá com água, melado e açúcar até reduzir bem.",
                    "Acrescente o leite de coco, misture e deixe ferver por alguns minutos.",
                    "Adicione o molho umami, misture e espere esfriar.",
                    "Em um prato acomode as folhas de alho-poró e coloque o vinagrete de jiló por cima.",
                    "Finalize com o molho e está pronto para servir. ",

                ],
            },
            Entradaveg3: {
                id: 6,
                Title: "Batata Frita Quentinha",
                Tempo: "20min",
                Rendimento: "2 porções",
                Ingredientes: [
                    "Batatas (quantidade a gosto) cortadas em palitos",
                    "Óleo",
                    "Amido de milho",
                ],
                Quantidade: [
                    "A gosto",
                    "Óleo sufisciente para cobrir as batatas",
                    "1/2 colher (sopa)"
                ],
                Preparo: [
                    "Corte as batas em palito e seque-as com papel toalha.",
                    "Coloque o óleo para esquentar, quando estiver bem quente, retire 1/2 xícara desse óleo e misture a 1/2 colher de amido de milho.",
                    "Após misturado, volte esse óleo para frigideira, frite as batatas em fogo médio até dourarem.",
                    "É uma dica que vale muito a pena, pois as batas ficam bem sequinhas.",

                ],
            },
            Entradaveg4: {
                id: 7,
                Title: "Homus de beterraba",
                Tempo: "45min",
                Rendimento: "2 porções",
                Ingredientes: [
                    "2 beterrabas",
                    "Sal",
                    "Pimenta",
                    "Azeite",
                    "Grão-de-bico cozido",
                    "Tahine",
                    "suco de limão",
                    "Zahtar",
                ],
                Quantidade: [
                    "2 unidades",
                    "A gosto",
                    "A gosto",
                    "1/2 xícara de chá",
                    "3 colheres de sopa",
                    "3 colheres de sopa",
                    "A gosto"

                ],
                Preparo: [
                    "Descasque as beterrabas e corte em 4 partes.",
                    "Coloque elas em um papel alumínio, tempere com sal, pimenta e um pouco de azeite.",
                    "Feche o papel alumínio formando uma trouxinha e leve para assar em forno preaquecido a 180 °C por 35 minutos.",
                    "Em um processador, coloque o grão-de-bico, as beterrabas cozidas, o Tahine, o suco de limão e o azeite.",
                    "Bata até virar uma pastinha.",
                    "Transfira para uma tigela, regue com mais azeite e polvilhe um mais pouco de Zahtar e está pronto."

                ],
            }

        },

        PratoPrincipal: {
            Prato1: {
                id: 0,
                Title: "Risoto de filé mignon",
                Tempo: "40min",
                Rendimento: "4 porções",
                Ingredientes: [

                    'filé mignon em cubos',
                    'Sal e pimenta-do-reino',
                    'azeite',
                    'sopa de manteiga sem sal',
                    'cebola picada',
                    'alho picados',
                    'arroz arbóreo',
                    'vinho branco',
                    'caldo de legumes',
                    'Queijo parmesão',
                    'Cheiro-verde',
                ],
                Quantidade: [
                    "500 gramas",
                    'a gosto',
                    '1 fio',
                    '2 colheres',
                    '1/2',
                    '2 dentes',
                    '2 xicaras',
                    '250 ml',
                    '1 unidade',
                    'a gosto',
                    'a gosto',
                ],
                Preparo: [
                    "Reúna todos os ingredientes;",
                    "Tempere a carne com sal, pimenta e misture;",
                    "Em uma panela, esquente um fio de azeite, sele o filé e reserve;",
                    "Na mesma panela, derreta 1 colher de sopa de manteiga e refogue a cebola até dourar;",
                    "Diminua o fogo, adicione o alho e deixe refogar;",
                    "Acrescente o arroz e refogue também;",
                    "Despeje o vinho e mexa sem parar;",
                    "Vá colocando o caldo de legumes gradualmente e mexendo sempre;",
                    "Conforme o caldo for secando, vá acrescentando e mexendo até o arroz ficar al dente;",
                    "Adicione o filé mignon, misture e desligue o fogo;",
                    "Salpique o parmesão ralado, acrescente a manteiga e misture até incorporar;",
                    "Finalize com o cheiro-verde e acerte o sal (caso precise);",
                    "Agora é só servir.",

                ],
            },
            Prato2: {
                id: 1,
                Title: "Farfalle limone com salmão",
                Tempo: "40min",
                Rendimento: "5 porções",
                Ingredientes: [
                    'farfalle',
                    'filé de salmão',
                    'queijo parmesão ralado',
                    'cebola roxa picada',
                    'pimenta-dedo-de-moça picada sem sementes',
                    'litro de creme de leite fresco',
                    'colher de sopa de dill (endro) picado',
                    'limões sicilianos',
                    'Pimenta e sal',
                    'Cebolinha',
                ],
                Quantidade: [
                    '500 gramas',
                    '700 gramas',
                    '50 gramas',
                    '1',
                    '1',
                    '1 litro',
                    '1 colher',
                    '2 limões',
                    'a gosto',
                ],
                Preparo: [
                    'Ferva água em uma panela para cozinhar o macarrão.',
                    'Tempere o filé de salmão com pimenta e sal e frite em uma frigideira aquecida com azeite por cerca de 3 minutos cada lado.',
                    'Retire o salmão do fogo, lasque o filé e reserve.',
                    'Junte na frigideira usada para fritar o salmão, a cebola e a pimenta-dedo-de-moça.',
                    'Adicione o creme de leite fresco assim que a cebola dourar e deixe reduzir em fogo baixo.',
                    'Retire o suco dos limões, aqueça levemente e acrescente na frigideira.',
                    'Adicione sal e pimenta-do-reino e mexa bem.',
                    'Coloque o macarrão para cozinhar.',
                    'Junte o salmão em lascas na frigideira do molho.',
                    'Adicione o dill picado, o queijo parmesão ralado, as raspas de limão e mexa bem.',
                    'Escorra o macarrão e junte com o molho.',
                    'Finalize com a cebolinha e sirva. Bom apetite.',

                ],
            },
            Prato3: {
                id: 2,
                Title: "Frango italiano",
                Tempo: "50 min",
                Rendimento: "5 porções",
                Ingredientes: [
                    'sopa de shoyu',
                    'xícara de chá de molho de tomate',
                    'colher de chá de mostarda dijon',
                    'vinho branco seco',
                    'peito de frango cortado em filés',
                    'azeite',
                    'cebola roxa              ',
                    'alho                  ',
                    'folhas de manjericão ',
                    'água                 ',
                    'mini tomates italianos',
                    'mussarela de búfala grande      ',
                    'Sal e pimenta-do-reino',
                ],
                Quantidade: [
                    '3 colheres',
                    '1 xícara',
                    '1 colher de chá',
                    '1/2 xícara de chá',
                    '600 gramas',
                    '3 colheres de sopa',
                    '1',
                    '2 dentes',
                    '2 colheres de sopa',
                    '1 xícara de chá',
                    '100 gramas',
                    '1',
                    'a gosto',
                ],
                Preparo: [
                    'Em um recipiente, coloque o shoyu, 3 colheres de sopa de molho de tomate, a mostarda dijon, 2 colheres de sopa de vinho branco e a pimenta-do-reino.',
                    'Misture e deixe marinar por pelo menos 30 minutos.',
                    'Preaqueça uma panela em fogo alto.',
                    'Quando estiver bem quente, coloque o frango.',
                    'Sele cada lado do filé por 2 minutos, sem mexer muito.',
                    'Retire-os da panela e reserve.',
                    'Na mesma panela, regue com um pouco de azeite, adicione a cebola e o alho picado, o sal e deixe refogar.',
                    'Acrescente o restante do vinho branco e deixe-o evaporar.',
                    'Volte com os peitos de frango para a panela.',
                    'Adicione também a marinada, o restante do molho de tomate e as folhas de manjericão.',
                    'Inclua a água e misture.',
                    'Deixe cozinhar por 10 minutos, mexendo na metade do tempo.',
                    'Acrescente os tomates.',
                    'Corte a mussarela em tiras e coloque por cima dos peitos de frango.',
                    'Tampe a panela e deixe cozinhar por 2 minutos.',
                    'Quando o queijo estiver derretido, acrescente mais folhas de manjericão e um pouco de pimenta-do-reino.',
                    'Está pronto para servir.',

                ],
            },
            Prato4: {
                id: 3,
                Title: "Sobrecoxa ao molho de cogumelos",
                Tempo: "50min",
                Rendimento: "6 porções",
                Ingredientes: [
                    'sobrecoxa',
                    'Sal',
                    'Pimenta-do-reino',
                    'cogumelo paris',
                    'cogumelo portobelo',
                    'vinho branco seco',
                    'amido de milho',
                    'Cheiro-verde',
                ],
                Quantidade: [
                    '1kg',
                    'a gosto',
                    'a gosto',
                    '200 gramas',
                    '200 gramas',
                    '400 ml',
                    '2 colheres de sopa',
                    'a gosto',
                ],
                Preparo: [
                    'Em uma vasilha, coloque as sobrecoxas e tempere com sal e pimenta.',
                    'Em uma frigideira, coloque as sobrecoxas e deixe dourar bem dos dois lados.',
                    'Retire e reserve.',
                    'Na mesma panela, adicione os cogumelos cortados em fatias e deixe-os al dente.',
                    'Despeje o vinho e ajuste o sal e a pimenta.',
                    'Em um copo, coloque um pouco do vinho e dissolva o amido.',
                    'Coloque essa mistura na panela e mexa bem.',
                    'Deixe ferver, retorne o frango e cozinhe por mais alguns minutos.',
                    'Finalize com cheiro-verde picadinho. Bom apetite.',

                ],
            },

        },
        PratoVeg: {
            PratoVeg1: {
                id: 4,
                Title: "Carbonara vegana",
                Tempo: "10 min",
                Rendimento: "1 porção",
                Ingredientes: [

                    'tofu',
                    'azeite',
                    'Molho de soja',
                    'Pimenta-preta',
                    'Páprica',
                    'Alho em pó',
                    'dentes de alho',
                    'cogumelos Paris',
                    'massa cozida',
                    'natas de soja',
                    'Sal',
                    'açafrão',
                    'Suco de limão',
                ],
                Quantidade: [
                    '100 gramas',
                    '1 fio',
                    'a gosto',
                    'a gosto',
                    'a gosto',
                    'a gosto',
                    '2 dentes',
                    '5',
                    '80 gramas',
                    '1/3 do pacote',
                    'a gosto',
                    '1 pitada',
                    'a gosto',
                ],
                Preparo: [
                    'Corte o tofu em retângulos e grelhe no azeite.',
                    'Tempere com molho de soja, páprica, pimenta e alho em pó.',
                    'Em outra frigideira, doure o alho picado por 2 minutos em fogo baixo.',
                    'Adicione os cogumelos picados e refogue por alguns minutos, mas não deixe murchar totalmente.',
                    'Corte o tofu em pedaços menores e adicione na frigideira com o alho picado.',
                    'Coloque a massa cozida, as natas de soja e tempere com sal, pimenta, alho em pó, páprica e açafrão.',
                    'Desligue o fogo e pingue algumas gotas de suco de limão por cima.',

                ],
            },
            PratoVeg2: {
                id: 5,
                Title: "Almôndegas de grão-de-bico veganas",
                Tempo: "20 min",
                Rendimento: "10 a 15 unidades",
                Ingredientes: [

                    'grão-de-bico cozido bem macio',
                    'cheiro-verde picado',
                    'água',
                    'cominho em pó',
                    'páprica defumada',
                    'alho pequeno (sem o miolo)',
                    'cebola picada',
                    'semente de gergelim (opcional)',
                    'Sal',
                    'Farinha de trigo para dar liga',
                    'Óleo para fritar',
                ],
                Quantidade: [
                    '2 xícaras de chá',
                    '4 colheres de sopa',
                    '6 colheres de sopa',
                    '1/2 colher de chá',
                    '1/2 colher de chá',
                    '1 dente',
                    '1/4',
                    '1 colher de sopa',
                    'a gosto',

                ],
                Preparo: [
                    'Em um processador, coloque todos os ingredientes (menos a farinha e o óleo) e processe até formar uma massa uniforme.',
                    'Adicione a farinha, gradualmente e vá misturando até dar liga.',
                    'Pegue pequenas porções da massa, molde em bolinhas e frite em óleo bem quente.',
                    'Agora é só servir. Bom apetite.',

                ],
            },
            PratoVeg3: {
                id: 6,
                Title: "Moqueca vegana",
                Tempo: "30min",
                Rendimento: "4 porções",
                Ingredientes: [
                    'azeite',
                    'alho',
                    'cebola',
                    'pimentão vermelho',
                    'pimentão amarelo',
                    'banana da terra madura',
                    'caju',
                    'palmito pupunha',
                    'Sal',
                    'Pimenta -do-reino',
                    'tomate',
                    'leite de coco',
                    'Pimenta- dedo - de - moça',
                    'Gengibre',
                    'Raiz de capim- santo',
                    'Coentro',
                ],
                Quantidade: [
                    '100 ml',
                    '15 gramas',
                    '100 gramas',
                    '60 gramas',
                    '60 gramas',
                    '200 gramas',
                    '100 gramas',
                    '160 gramas',
                    'a gosto',
                    '120 gramas',
                    '300 ml',
                    'a gosto',
                    'a gosto',
                    'a gosto',
                    'a gosto',

                ],
                Preparo: [
                    'Em uma frigideira, coloque azeite, o alho e deixe dourar.',
                    'Adicione a cebola, os pimentões e refogue bem.',
                    'Acrescente a banana, o caju, o palmito e tempere com sal e pimenta-do-reino.',
                    'Refogue por mais três minutos e junte os demais ingredientes.',
                    'Cozinhe por mais cinco minutos e sirva em seguida.',
                    'Sirva e bom apetite.',

                ],
            },
            PratoVeg4: {
                id: 7,
                Title: "Feijoada vegana",
                Tempo: "50min",
                Rendimento: "4 porções",
                Ingredientes: [

                    'gramas de tofu frescal',
                    'gramas de tofu defumado',
                    'Óleo',
                    'cebola grande cortada em cubinhos',
                    'dentes de alho picados',
                    'feijão-preto (12 horas de molho)',
                    'Água',
                    'chuchu descascado e picado rusticamente',
                    'cenoura pequena cortada em rodelas diagonais',
                    'batata-doce pequena cortada em rodelas',
                    'laranja inteira',
                    'pimenta-dedo-de-moça',
                ],
                Quantidade: [
                    '120 gramas',
                    '120 gramas',
                    'a gosto',
                    '1',
                    '3 a 4 dentes',
                    '1 xícara de chá',
                    'o quanto bastar',
                    '1/2 ',
                    '1',
                    '1',
                    '1',
                    '1/2',
                ],
                Preparo: [
                    'Retire as cascas do tofu defumado, corte elas em lascas e o tofu em cubinhos pequenos. Reserve o tofu com o alho.',
                    'O tofu frescal, pique em cubos maiores.',
                    'Em uma panela, esquente o óleo o suficiente para fritura e frite os cubos de tofu frescal e as cascas do tofu defumado. Reserve.',
                    'Em uma panela grande, esquente um fio de alho e refogue a cebola até ela começar a caramelizar.',
                    'Adicione o alho, o tofu defumado, misture bem e deixe refogar até dourar bem.',
                    'Acrescente o feijão e dê uma leve refogada.',
                    'Cubra com água e deixe ferver por cerca de 40 minutos.',
                    'Enquanto isso, em uma frigideira, esquente 1 fio de óleo e grelhe os legumes. Reserve.',
                    'Corte a laranja em rodelas e coloque para cozinhar com o feijão.',
                    'Junte a pimenta-dedo-de-moça e misture bem.',
                    'Assim que o feijão cozinhar e o caldo engrossar, retire as rodelas de laranja, adicione os legumes grelhados, o tofu frito, 1/2 xícara de água, misture e deixe cozinhar por mais 10 minutos.',
                    'Sirva com arroz, farofa vegana e couve refogada. Bom apetite.',

                ],
            }
        },
        Sobremesa: {
            Sobremesa1: {
              id: 0,
              Title: "Pudim",
              Tempo: "60 min",
              Rendimento: "8 porções",
              Ingredientes: [
                "leite condensado",
                "leite (medida da lata de leite condensado)",
                "ovos inteiros",
                "1 xícara (chá) de açúcar",
                "1/2 xícara de água",
              ],
              Quantidade: ["1 lata", "1 lata", "3", "1 xícara", "1/2 xícara"],
              Preparo: [
                "Pudim",
                "Primeiro, bata bem os ovos no liquidificador",
                "Acrescente o leite condensado e o leite, e bata novamente",
                "Calda",
                "Derreta o açúcar na panela até ficar moreno, acrescente a água e deixe engrossar.",
                "Coloque em uma forma redonda e despeje a massa do pudim por cima.",
                "Asse em forno médio por 45 minutos, com a assadeira redonda dentro de uma maior com água.",
                "Espete um garfo para ver se está bem assado.",
                "Deixe esfriar e desenforme.",
              ],
            },
            Sobremesa2: {
              id: 1,
              Title: "Manjar de coco",
              Tempo: "20 min",
              Rendimento: "20 porções",
              Ingredientes: [
                "leite",
                "leite de coco",
                "coco ralado seco sem açúcar",
                "amido de milho",
                "açúcar",
              ],
              Quantidade: [
                "1 litro",
                "1 vidro pequeno",
                "100g",
                "6 colheres (sopa)",
                "8 colheres (sopa)",
              ],
      
              Preparo: [
                "Coloque o leite, o açúcar, o leite de coco e o coco ralado em uma panela, misture bem.",
                "Leve ao fogo e junte o amido de milho dissolvido em um copo de leite.",
                "Mexa sempre até engrossar, aguarde mais um minuto.",
                "Despeje em uma forma decorada, untada com óleo ou simplesmente molhada.",
                "Deixe esfriar e leve à geladeira por 2 horas.",
                "Sirva com calda de ameixa ou calda de morangos.",
              ],
            },
            Sobremesa3: {
              id: 2,
              Title: "Petit gateau",
              Tempo: "30 min",
              Rendimento: "8 porções",
              Ingredientes: [
                "chocolate meio amargo",
                "manteiga sem sal",
                "açúcar",
                "farinha de trigo",
                "ovos inteiros (tire a pele da gema)",
                "gemas",
              ],
              Quantidade: [
                "200g",
                "2 colheres",
                "1/4 xícara (chá)",
                "2 colheres",
                "2",
                "2",
              ],
              Preparo: [
                "Derreta a manteiga e o chocolate em banho-maria.",
                "Bata os ovos e as gemas com açúcar na batedeira, até ficar bem claro.",
                "Junte o chocolate derretido e a farinha de trigo, misturando com uma espátula.",
                "Depois, unte as forminhas de empadinha, passe farinha de trigo e coloque a massa.",
                "Preaqueça o forno e leve para assar de 6 a 10 minutos (em fogo alto) até os bolinhos crescerem, mas o meio deve ficar molinho.",
                "Deve-se desenformar ainda quente.",
                "Sirva diretamente no prato, acompanhado com sorvete de creme.",
              ],
            },
            Sobremesa4: {
              id: 3,
              Title: "Banoffe de banana",
              Tempo: "30 min",
              Rendimento: "8 porções",
              Ingredientes: [
                "biscoito maisena",
                "margarina (em temperatura ambiente)",
                "chantilly",
                " doce se leite",
                "bananas nanicas",
              ],
              Quantidade: ["2 pacotes", "1 e 1/2 xícara", "400 g", "1 lata", "5"],
              Preparo: [
                "Triture o biscoito e misture com a margarina até virar uma massa que dê para forrar a forma.",
                "Coloque no forno por 7 minutos.",
                "Dentro da forma, coloque uma camada de bananas e uma camada de doce de leite e cubra com chantilly.",
                "Polvilhe canela para decorar e sirva gelado.",
              ],
            },
          },
          SobremesaVeg: {
            SobremesaVeg1: {
              id: 4,
              Title: "Pudim de chia simples",
              Tempo: "80min",
              Rendimento: "1 porção grande ou 2 pequenas",
              Ingredientes: [
                "leite de coco",
                "sementes de chia",
                "mel (ou qualquer adoçante )",
                "Frutas",
              ],
              Quantidade: [
                "1 xícara de chá",
                "4 colheres de sopa ",
                "2 colheres de sopa",
                "a gosto",
              ],
              Preparo: [
                "Em um recipiente, adicione o leite de coco, a chia, o mel e misture bem",
                "Leve para a geladeira por no mínimo 1 hora para ganhar consistência",
                "Agora é só montar: faça camadas do pudim intercalando com frutas em um potinho de vidro",
                "Leve para a geladeira e deixe por mais 4 horas, ou de um dia para o outro",
                "Agora é só servir.",
              ],
            },
            SobremesaVeg1: {
              id: 5,
              Title: "Mousse de pitaya",
              Tempo: "40min",
              Rendimento: "4 a 6 porções",
              Ingredientes: [
                "pitaya rosa",
                " castanhas demolhadas",
                "leite de coco caseiro",
                "Stevia",
                "Baunilha",
                "óleo de coco",
              ],
              Quantidade: ["1", "3 colheres de sopa", "120 ml", "a gosto", "a gosto"],
              Preparo: [
                "Coloque todos os ingredientes no liquidificador (menos o óleo de coco) e bata até ficar bem homogêneo.",
                "Adicione o óleo de coco e bata até incorporar.",
                "Transfira a mousse para taças ou um refratário e leve para a geladeira por cerca de 35 minutos.",
                "Agora é só servir. Bom apetite.",
              ],
            },
            SobremesaVeg1: {
              id: 6,
              Title: "Pavê vegano",
              Tempo: "20min",
              Rendimento: "10 porções",
              Ingredientes: [
                "leite vegetal",
                "amido de milho",
                "açúcar demerara",
                "extrato de baunilha",
                "cacau em pó",
                "chocolate 50% vegano",
                "Bolacha maisena vegana (ou de aveia)",
                "Morango",
              ],
              Quantidade: [
                "1 litro",
                "4 colheres de sopa",
                "6 colheres de sopa",
                "1 colher de chá",
                "4 colheres de sopa",
                "6 quadradinhos",
                "",
                "a gosto",
              ],
              Preparo: [
                "Em uma panela, coloque o leite, o amido e misture bem até diluir.",
                "Leve para cozinhar em fogo baixo e acrescente o açúcar.",
                "Cozinhe por quinze minutos até engrossar.",
                "Em uma vasilha, coloque metade do creme, adicione a baunilha, misture bem e reserve.",
                "Com a outra metade do creme ainda no fogo, acrescente o cacau, o chocolate, misture até tudo incorporar e reserve.",
                "Para a montagem, intercale camadas de creme de chocolate, creme branco, bolacha e morango ou a forma que preferir.",
                "Agora é só servir! Bom apetite.",
              ],
            },
            SobremesaVeg1: {
              id: 7,
              Title: "Brigadeiro de capim-limão",
              Tempo: "60min",
              Rendimento: "4 a 6 porções",
              Ingredientes: [
                "inhame médio cozido e sem casca",
                "capim-limão fresco picado",
                "água",
                "açúcar demerara",
                " cacau em pó 100%"
              ],
              Quantidade: [
                "1",
                "1 xícara de chá",
                "1 xícara de chá",
                "1/4 de xícara de chá",
                "1 colher de sobremesa"
              ],
              Preparo: [
                "No liquidificador, coloque o inhame cozido, a água, o capim-limão e bata até formar um creme homogêneo.",
                "Coe o creme, transfira para uma panela, adicione o restante dos ingredientes e misture bem.",
                "Leve para o fogo médio e mexa sem parar por cerca de 20 minutos ou até começar a desgrudar da panela.",
                "Despeje em um prato e leve para a geladeira por 30 minutos.",
                "Agora é só servir. Bom apetite.",
              ],
      
            },
             SobremesaVeg1: {
              id: 8,
              Title: "Trufa de coco com damasco",
              Tempo: "25min",
              Rendimento: " 15 a 20 porções",
              Ingredientes: [
                "damasco seco",
                "coco ralado sem açúcar",
                "Whey Protein neutro ou de baunilha (proteína em pó vegana ou colágeno hidrolisado)",
                "água"
              ],
              Quantidade: [
                "1 xícara de chá",
                "1 xícara de chá",
                "30 g",
               "1/4 de xícara",
              ],
              Preparo: [
                "Em um processador (ou liquidificador), adicione todos os ingrediente e bata até formar uma massa uniforme e mais firme.",
                "Umedeça as mãos, pegue pequenas porções da massa e molde em formato de bolinhas do tamanho que desejar.",
                "Disponha em um recipiente e leve para a geladeira por 15 minutos.",
                "Agora é só servir! Bom apetite."
      
              ],
             }
          },
    }

]
